//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cafe.bd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cafeEntities : DbContext
    {
        public cafeEntities()
            : base("name=cafeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
       

        public virtual DbSet<Gang> Gangs { get; set; }
        public virtual DbSet<Gang_user> Gang_user { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Menu_category> Menu_category { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Order_menu> Order_menu { get; set; }
        public virtual DbSet<Roly> Rolies { get; set; }
        public virtual DbSet<Status_cook> Status_cook { get; set; }
        public virtual DbSet<Status_pay> Status_pay { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        private static cafeEntities _context;

        public static cafeEntities GetContext()
        {
            if (_context == null)
                _context = new cafeEntities();
            return _context;
        }
    }
}
