//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cafe.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_menu
    {
        public Nullable<int> id_order { get; set; }
        public Nullable<int> id_menu { get; set; }
        public int id_order_menu { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Order Order { get; set; }
    }
}
