//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cafe.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_menu = new HashSet<Order_menu>();
        }
    
        public int id_order { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> Number_desk { get; set; }
        public Nullable<int> id_status_cook { get; set; }
        public Nullable<int> id_status_pay { get; set; }
        public Nullable<int> Number_people { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_menu> Order_menu { get; set; }
        public virtual Status_cook Status_cook { get; set; }
        public virtual Status_pay Status_pay { get; set; }
        public virtual User User { get; set; }
    }
}
